netfs, cachefiles: include linux/bio.h for BIO_MAX_VECS
The newly added code causes a build failure without this in some configurations:

fs/cachefiles/io.c: In function 'cachefiles_prepare_write_subreq':
fs/cachefiles/io.c:633:31: error: 'BIO_MAX_VECS' undeclared (first use in this function); did you mean 'BIO_MAX_SECTORS'?
  633 |         subreq->max_nr_segs = BIO_MAX_VECS;
      |                               ^~~~~~~~~~~~
      |                               BIO_MAX_SECTORS
fs/cachefiles/io.c:633:31: note: each undeclared identifier is reported only once for each function it appears in

Fixes: 0d393b1a6699 ("netfs, cachefiles: Implement helpers for new write code")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Link: https://lore.kernel.org/r/20240404123414.2675384-1-arnd@kernel.org
Signed-off-by: Christian Brauner <brauner@kernel.org>