mm: Fix build failure due to missing build time check
/tmp/next/build/mm/hugetlb_cgroup.c: In function 'hugetlb_cgroup_cfttypes_init':
/tmp/next/build/mm/hugetlb_cgroup.c:840:42: error: 'struct cftype' has no member named 'lockdep_key'
  840 |                 lockdep_register_key(&cft->lockdep_key);
      |                                          ^~

Signed-off-by: Mark Brown <broonie@kernel.org>